name: secret print
on:
  push:
    branches:
      - main

jobs:
  secretprint:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Secret
        run: "echo ${{secrets.MONGODB_PASSWORD}} >> ./sample.txt"
      - name: Upload the artifact in artifact registry
        uses: actions/upload-artifact@v7
        with: 
          name: sample
          path: ./sample.txt